### ISSUE TITLE
Unable to build this branch on my macBook

### ISSUE THREAD

**Issue by rlnktt** [pfalcon/pycopy#23]
make: *** No rule to make target `lib/lwip/src/core/def.c', needed by `build-PYBV11/genhdr/qstr.i.last'.  Stop.

I'm getting the above error , while trying to build this on my mac!!

Command that I issued:
make clean
make BOARD=PYBV11

**Comment by pfalcon** [comment]
Likely reason is not having checked out the submodules, as described in the README.
