### ISSUE TITLE
ure: mixing named classes and characters in a match set raises ValueError

### ISSUE THREAD

**Issue by c0d3z3r0** [pfalcon/pycopy#29]
Tested on `unix` and `esp8266`, master branch

~~~
>>> ure.compile('\d+')
<re 3fff02f0>

>>> ure.compile('[abc0-9]+')
<re 3fff0580>

>>> ure.compile('[abc\d]+')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Error in regex

>>> ure.compile('[\w\d]+')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Error in regex
~~~

**Comment by pfalcon** [comment]
Yes, this was never supported (never parsed properly), With recent changes (WIP so far), any (well, most) unsupported regex syntax now raises an error instead of silent unexpected behavior.

**Comment by pfalcon** [comment]
Ok, these changes are finished now. Nothing really new from when this issue was posted, they were just promoted from "WIP" to "finalized". The docs were updated yet then too: https://pycopy.readthedocs.io/en/latest/library/ure.html
