### ISSUE TITLE
Relationship of this fork to Zephyr

### ISSUE THREAD

**Issue by pkral78** [pfalcon/pycopy#33]
I come across this fork just by accident, so forgive me if this question has already been answered before.

Will some target platform be dealt with a priority within this fork? (By some, I mean Zephyr of course.) Or it is intended to be platform agnostic.

There would be some obvious advantages to focus on Zephyr, I'll just point to some:
- as Zephyr HAL is gradually promoting, we could adapt it to Python. On Zephyr HAL side there is also clear definition of synchronous or asynchronous API. I think that peripheral AIO API with async/await is missing for a long time.
- Zephyr's subsystems (for example BLE/Mesh and Mesh model representation by Python objects)

We know that @pfalcon is long term Zephyr collaborator, so please share your PoV.

**Comment by pfalcon** [comment]
This fork is my personal project (== maintained in my own free time), not directly related to Zephyr or Zephyr port. In my own free time, I'm more interested to work on generic language-level things (i.e. "platform agnostic"), and on the leading OS platform - POSIX, using Linux as a reference implementation platform.

While I'd be interested to work on Zephyr port, I simply won't have resources to do that in my own free time, so would work on it only as much work allows that. And my work just tangentially touches MicroPython from time to time. So, I'd be glad to work on Zephyr port, if my work assignments allow that.

Hopefully, that clarifies the situation.
