### ISSUE TITLE
modlwip.c does not properly return POLL_HUP and POLL_ERR socket errors

### ISSUE THREAD

**Issue by t35tB0t** [pfalcon/pycopy#38]
extmod/modlwip.c only returns POLL_HUP and POLL_ERR if the events flags specify them. AFIAK this is not AFAIK POSIX compliant which specifies these return events shall be unsolicited. e.g. see http://man7.org/linux/man-pages/man2/poll.2.html

The impact is that uasyncio (which does not set POLL_HUP and POLL_ERR flags) will not see these failed socket connections and co-routines will hang and consume memory. Eventually pycopy will run out of memory. Adding these flags to uasyncio is a work-around to getting the socket errors returned but is not the expected behavior of these ioctl polls. The modlwip.c changes below were tested and, work when appropriate exception handling is added to uasync (specifically in the start_server() loop). Socket errors will also now be returned the the yielding co-routine where appropriate exception handling including stream read.aclose() and write.aclose() must be called to clean up upon pre-mature connection termination.

[extmod_modlwip_c.diff.txt](https://github.com/pfalcon/pycopy/files/3684560/extmod_modlwip_c.diff.txt)

note: In diff, (flags,ret) renamed to (events,revents) to align with common parlance in ioctl polling

**Comment by pfalcon** [comment]
Handled in upstream.
