### ISSUE TITLE
STM32H7 Ethernet

### ISSUE THREAD

**Issue by rcordeau** [pfalcon/pycopy#47]
Hi,
Is there any plan on getting eth.c to work with the STM32H7 chip? Right now it doesn't work (H7 registers are different).

**Comment by pfalcon** [comment]
Pycopy is a programming language project, so it's concerned with things like JIT, object inheritance, buffered streams, etc., not things like supporting drivers for a particular hardware. In this regard, it's similar to CPython. Supporting particular hardware is up to its maintainers.
