### ISSUE TITLE
poll(timeout) feature is missing

### ISSUE THREAD

**Issue by joyhope** [pfalcon/pycopy#60]
I  called  select.poll(1000),  it seems not working.  I call select.poll(),  it works. 

It is the poll implement problem, or  I used the wrong dependance library.

**Comment by pfalcon** [comment]
Which port do you use? How to reproduce this issue? Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for more information.

**Comment by joyhope** [comment]
I use port/unix/pycopy.  Strange, I pull the related code from my application, the poll(1000) works.  I try study the problem.

**Comment by joyhope** [comment]
Sorry,  my code problem. The parameter becomes 1000.0 , so it is unable to work.
