### ISSUE TITLE
Fail to install pycopy-termios.

### ISSUE THREAD

**Issue by DreamEdm** [pfalcon/pycopy#63]
I want to install termios  but I can't.
When we use
$ pip install pycopy-termios
It rase 
'''
ERROR: File "setup.py" not found for legacy project pycopy-lib from https://files.pythonhosted.org/packages/4a/0e/79682be709fae5dee8dfae20fa7782707f349931eafdeada0cfd55a46db9/pycopy-lib-0.2.2.tar.gz#sha256=df1ac81085dd643e8db2326150098abdd58f1d8b78c1e74b5e39d9889161c6e5.
'''
My python version is 3.6.5, windows11
What should I do?

**Comment by pfalcon** [comment]
pycopy modules are not supposed to be installed with pip, but rather upip. Please read the manual at https://pycopy.readthedocs.io/en/latest/
